[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

# ------------------------------
# Make debug
# ~$ cargo make
# ------------------------------
[tasks.clean-www]


[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.debug]
dependencies = [
    "format",
    "build",
]

[tasks.default]
alias = "debug"

# ------------------------------
# Make release
# ~$ cargo make release
#-------------------------------
[tasks.format-release]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["format-release"]

[tasks.release]
dependencies = [
    "format-release",
    "build-release",
]
