[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

# ------------------------------
# Debug
# ~$ cargo make
# ------------------------------

[tasks.run]
command = "cargo"
args = ["run", "debug"]
dependencies = ["debug"]

[tasks.default]
alias = "run"


# ------------------------------
# Release
# ~$ cargo make release
# ------------------------------

[tasks.release]
command = "cargo"
args = ["run", "release"]
dependencies = ["build-release"]
